apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = alertmanager73@gmail.com
    password = data_lake
    from_address = alertmanager73@gmail.com
    from_name = Grafana Alerts
    skip_verify = true
    startTLS_policy = ForceStartTLS
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: grafana-operator
  creationTimestamp: "2024-10-14T07:28:09Z"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.2
    helm.sh/chart: grafana-8.5.5
  name: grafana
  namespace: grafana-operator
  resourceVersion: "3416620"
  uid: 14594add-55c9-444b-8f9d-c12d0897c1af
